export type IconName =
  | 'user'
  | 'mail'
  | 'lock'
  | 'eye-open'
  | 'eye-close'
  | 'search'
  | 'rate'
  | 'calendar'
  | 'arrow-right'
  | 'edit'
  | 'headset'
  | 'tel'
  | 'document-check'
  | 'heart'
  | 'user-active'
  | 'user-inactive'
  | 'home-active'
  | 'home-inactive'
  | 'plant-active'
  | 'plant-inactive'
  | 'add-circle'
  | 'water-drop'
  | 'sun'
  | 'edit-white'
  | 'check-circle'
  | 'content';

export const getIcon = (iconName: IconName) => {
  switch (iconName) {
    case 'user':
      return require('@assets/icons/user.png');
    case 'mail':
      return require('@assets/icons/mail.png');
    case 'lock':
      return require('@assets/icons/lock.png');
    case 'eye-open':
      return require('@assets/icons/eye-open.png');
    case 'eye-close':
      return require('@assets/icons/eye-close.png');
    case 'search':
      return require('@assets/icons/search.png');
    case 'rate':
      return require('@assets/icons/rate.png');
    case 'calendar':
      return require('@assets/icons/calendar.png');
    case 'arrow-right':
      return require('@assets/icons/arrow-right.png');
    case 'edit':
      return require('@assets/icons/edit.png');
    case 'headset':
      return require('@assets/icons/headset.png');
    case 'tel':
      return require('@assets/icons/tel.png');
    case 'document-check':
      return require('@assets/icons/document-check.png');
    case 'heart':
      return require('@assets/icons/heart.png');
    case 'user-active':
      return require('@assets/icons/navbar/user-active.png');
    case 'user-inactive':
      return require('@assets/icons/navbar/user-inactive.png');
    case 'home-active':
      return require('@assets/icons/navbar/home-active.png');
    case 'home-inactive':
      return require('@assets/icons/navbar/home-inactive.png');
    case 'plant-active':
      return require('@assets/icons/navbar/plant-active.png');
    case 'plant-inactive':
      return require('@assets/icons/navbar/plant-inactive.png');
    case 'add-circle':
      return require('@assets/icons/add-circle.png');
    case 'water-drop':
      return require('@assets/icons/water-drop.png');
    case 'sun':
      return require('@assets/icons/sun.png');
    case 'check-circle':
      return require('@assets/icons/check-circle.png');
    case 'edit-white':
      return require('@assets/icons/edit-white.png');
    case 'content':
      return require('@assets/icons/content.png');
  }
};
